package com.example.Student_Library_Management_System.Service;

import com.example.Student_Library_Management_System.Enums.CardStatus;
import com.example.Student_Library_Management_System.Models.Card;
import com.example.Student_Library_Management_System.Models.Student;
import com.example.Student_Library_Management_System.Repository.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class StudentService {

    @Autowired
    StudentRepository studentRepository;

    public String createStudent(Student student){
        //Student from postman is already the basic attribute set

        //Card should be autogenerated, when the create student function gets called
        Card card = new Card();
        card.setCardStatus(CardStatus.ACTIVATED);
        card.setStudentVariableName(student); //Using this attribute the foreign key will be set

        //Let's go to the student
        student.setCard(card);

        //if there was unidirectional mapping we have to save both of them

        // In bidirectional mapping child will be automatically saved

        studentRepository.save(student);

        //By cascading effect , child will be automatically saved.

        return "Student and Card added!";
    }
}
